# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: the sky is mine
email: 651019063@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  only do but say
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: menghuanwd
github_username:  menghuanwd
zhihu_username: menghuanwd
RSS: false
sidebar: true
paginate: 10

# Build settings
markdown: kramdown
theme: minima
# theme: jekyll-theme-minimal
# theme: jekyll-theme-hacker
# theme: jekyll-theme-midnight

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-gist

# # Pagination Settings
# pagination:
#   enabled: true
#   per_page: 5
#   # offset: 2
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# permalink: /:year/:month/:title.html

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
